# This file was auto-generated by eo2py-maven-plugin
# on 2021.06.27 at 19:07:31. Don't edit it,
# your changes will be discarded on the next build.
# The sources were compiled to XML
# by the EO compiler v.0.1.25.

from eo2py.atoms import *

"""
+package sandbox

[n] > fibonacci
  if. > @
    n.less 2
    n
    add.
      fibonacci (n.sub 1)
      fibonacci (n.sub 2)

<EOF>
"""


class EOfibonacci(ApplicationMixin, Object):

    def __init__(self):
        self.attr__self = self
        self.attr__parent = DataizationError()

        self.attr_n = DataizationError()

        self.attributes = ["n", ]

    @property
    def attr__phi(self):
        return (Attribute((Attribute((self.attr_n), "less")(Number(2))), "if")(self.attr_n)(
            Attribute((EOfibonacci()(Attribute((self.attr_n), "sub")(Number(1)))), "add")(
                EOfibonacci()(Attribute((self.attr_n), "sub")(Number(2))))))


import pytest
from .utils import fibonacci


@pytest.mark.parametrize("n", list(range(1, 10)))
def test_simple_fibonacci(n):
    res = EOfibonacci()(Number(n))
    assert res.dataize() == Number(fibonacci(n))
