# This file was auto-generated by eo2py-maven-plugin
# on 2021.07.03 at 21:48:08. Don't edit it,
# your changes will be discarded on the next build.
# The sources were compiled to XML
# by the EO compiler v.0.1.25.

from eo2py.atoms import *
from functools import partial

"""
[arg1 arg2 varargs...] > obj
  stdout > @
    sprintf
      "%d %d %d"
      arg1
      arg2
      get.
        varargs
        3

<EOF>
"""


class EOobj(ApplicationMixin, Object):
    def __init__(self):
        self.attr__self = self
        self.attr__parent = DataizationError()

        self.attr_arg1 = DataizationError()
        self.attr_arg2 = DataizationError()
        self.attr_varargs = Array()

        self.attributes = [
            "arg1",
            "arg2",
            "varargs",
        ]

        self.varargs = True

    @property
    def attr__phi(self):
        return Stdout()(
            Sprintf()((String("%d %d %d")))(self.attr_arg1)(self.attr_arg2)(
                Attribute((self.attr_varargs), "get")((Number(3)))
            )
        )


import pytest


def test_args_varargs(capsys):
    app1 = EOobj()(Number(-55))(Number(-88))(Number(0))(Number(1))(Number(2))(Number(3))(Number(4))
    assert app1.dataize()
    assert "-55 -88 3" in capsys.readouterr().out
    app2 = EOobj()(Number(-55))(Number(-88))
    with pytest.raises(IndexError) as e:
        assert app2.dataize()
    app3 = EOobj()(Number(-55))
    with pytest.raises(NotImplementedError) as e:
        assert app3.dataize()
