# This file was auto-generated by eo2py-maven-plugin
# on 2021.07.03 at 21:35:00. Don't edit it,
# your changes will be discarded on the next build.
# The sources were compiled to XML
# by the EO compiler v.0.1.25.

from eo2py.atoms import *
from functools import partial

"""
[attr] > a
  attr > a_attr

[] > b
  a "something" > @

[] > c
  b > @

[] > d
  c > @

[args...] > app
  stdout > @
    sprintf
      "%s\n"
      d.a_attr
<EOF>
"""


class EOa(ApplicationMixin, Object):
    def __init__(self):
        self.attr__self = self
        self.attr__parent = DataizationError()
        self.attr__phi = DataizationError()
        self.attr_attr = DataizationError()

        self.attributes = [
            "attr",
        ]

    @property
    def attr_a_attr(self):
        return self.attr_attr


class EOb(ApplicationMixin, Object):
    def __init__(self):
        self.attr__self = self
        self.attr__parent = DataizationError()

        self.attributes = []

    @property
    def attr__phi(self):
        return EOa()((String("something")))


class EOc(ApplicationMixin, Object):
    def __init__(self):
        self.attr__self = self
        self.attr__parent = DataizationError()

        self.attributes = []

    @property
    def attr__phi(self):
        return EOb()


class EOd(ApplicationMixin, Object):
    def __init__(self):
        self.attr__self = self
        self.attr__parent = DataizationError()

        self.attributes = []

    @property
    def attr__phi(self):
        return EOc()


class EOapp(ApplicationMixin, Object):
    def __init__(self):
        self.attr__self = self
        self.attr__parent = DataizationError()

        self.attr_args = Array()

        self.attributes = [
            "args",
        ]

        self.varargs = True

    @property
    def attr__phi(self):
        return Stdout()(Sprintf()((String("%s\n")))(Attribute((EOd()), "a_attr")))



def test_chained_phi(capsys):
    assert EOapp().dataize()
    assert 'something' in capsys.readouterr().out
