# This file was auto-generated by eo2py-maven-plugin
# on 2021.07.03 at 22:04:43. Don't edit it,
# your changes will be discarded on the next build.
# The sources were compiled to XML
# by the EO compiler v.0.1.25.

from eo2py.atoms import *
from functools import partial

"""
[name] > person
<EOF>
"""


class EOperson(ApplicationMixin, Object):
    def __init__(self):
        self.attr__self = self
        self.attr__parent = DataizationError()
        self.attr__phi = DataizationError()
        self.attr_name = DataizationError()

        self.attributes = [
            "name",
        ]


import pytest


def test_person():
    with pytest.raises(ApplicationError) as e:
        assert EOperson()(String("David"))(String("Bowie"))
    with pytest.raises(NotImplementedError) as e:
        assert EOperson()(String("Kate")).dataize()
    assert Attribute(EOperson()(String("Kate")), "name").dataize().data() == "Kate"
