# This file was auto-generated by eo2py-maven-plugin
# on 2021.07.03 at 22:08:36. Don't edit it,
# your changes will be discarded on the next build.
# The sources were compiled to XML
# by the EO compiler v.0.1.25.

from eo2py.atoms import *
from functools import partial

"""
[args...] > appArray
  stdout > @
    sprintf
      "%d"
      get.
        args
        3
<EOF>
"""


class EOappArray(ApplicationMixin, Object):
    def __init__(self):
        self.attr__self = self
        self.attr__parent = DataizationError()

        self.attr_args = Array()

        self.attributes = [
            "args",
        ]

        self.varargs = True

    @property
    def attr__phi(self):
        return Stdout()(
            Sprintf()((String("%d")))(Attribute((self.attr_args), "get")((Number(3))))
        )


def test_simple_varargs(capsys):
    app = EOappArray()(Number(1))(Number(2))(Number(3))(Number(4))(Number(5))
    assert app.dataize()
    assert "4" in capsys.readouterr().out
